name: youtube_darker
description: My personal project for a socail media application.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  firebase_analytics: ^6.0.2
  provider: ^4.3.2+2
  flutter_local_notifications: 3.0.1+7
  connectivity: ^2.0.2
  http: ^0.12.2
  share: ^0.6.5+4
  marquee: ^1.6.1
  flutter_signin_button: ^1.1.0
  pull_to_refresh: ^1.6.3
  cupertino_icons:
  image_picker: ^0.6.7+14

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launchIcon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launchIcon.png"

flutter_native_splash:
  image: "assets/images/splashIcon.png"
  color: "FFFFFF"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
